engine: python
recipe: upset
data:
  file: input_set_membership.csv
  x: null
  y: null
  fill: null
  facet: null
  time: null
  event: null
  annotation: null
  covariates: null
test:
  method: auto
  paired: false
  p_adjust: none
appearance:
  theme: pubplot_house
  palette: null
  x_label: null
  y_label: null
  title: null
  y_limits:
  - null
  - null
  show_points: true
  geom: box
  bracket:
    show: true
    label: p.signif
  scale: row
  cluster: both
