engine: r
recipe: survival_km
data:
  file: input_arm.csv
  x: arm
  'y': ~
  fill: ~
  facet: ~
  time: time
  event: event
  annotation: ~
  id: ~
  group: ~
  label: ~
  covariates: ~
test:
  method: auto
  paired: no
  p_adjust: none
appearance:
  theme: pubready_house
  palette: ~
  x_label: Months
  y_label: ~
  title: ~
  y_limits:
  - ~
  - ~
  show_points: yes
  geom: box
  bracket:
    show: yes
    label: p.signif
  scale: row
  cluster: both
  fc_cutoff: 1.0
  p_cutoff: 0.05
  top_n: 15.0
  pd_threshold: 20.0
  pr_threshold: -30.0
